<header>
    <nav class="navbar navbar-default navbar-main    lightHeader " role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $GLOBALS['SITE_APP_URL'] ?>"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown singleDrop active">
                        <a href="<?= $GLOBALS['SITE_APP_URL'] ?>">Home</a>
                    </li>
                    <li class="dropdown singleDrop">
                        <a href="<?= $GLOBALS['SITE_APP_URL'] ?>/pakagelist">tour packages</a>
                    </li>
                    <li class="dropdown singleDrop">
                        <a href="<?= $GLOBALS['SITE_APP_URL'] ?>/aboutus">about us</a>
                    </li>
                    <li class="dropdown singleDrop">
                        <a href="<?= $GLOBALS['SITE_APP_URL'] ?>/contactus">contact us</a>
                    </li>
                    <li class="dropdown singleDrop">
                        <a href="<?= $GLOBALS['SITE_APP_URL'] ?>/gallery">gallery</a>
                    </li>             
                    <li class="dropdown searchBox">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="searchIcon"><i class="fa fa-search" aria-hidden="true"></i></span></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <span class="input-group">
                                    <input type="text" class="form-control" placeholder="Search..." aria-describedby="basic-addon2">
                                    <span class="input-group-addon" id="basic-addon2">Search</span>
                                </span>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
</header>


<!-- DASHBOARD MENU  -->
<section class="dashboardMenu">
    <nav class="navbar dashboradNav">
        <div class="container">
            <div class="dashboardNavRight">
                <ul class="NavRight">
                    <li class="dropdown singleDrop">
                        <a href="#" class=" " data-toggle="" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bell" aria-hidden="true"></i> <span class="notifyNumber">2</span></a>
                        <ul class="dropdown-menu dropdownMenu">
                            <li>
                                <a href="#">
                                    <h4>information</h4>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <h5>Maldive Tour Packages</h5>
                                    <p>6 Hours Ago</p>
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <h5>London Tour Booking</h5>
                                    <p>15 Hours Ago</p>
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <h5>Maldive Tour Packages</h5>
                                    <p>2 Hours Ago</p>
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown singleDrop">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="img\dashboard\dash-user.jpg" alt=""><i class="fa fa-angle-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu dropdownMenu">
                            <li><a href="profile.html"><h5>Profile</h5></a></li>
                            <li><a href="setting.html"><h5>Account Settings</h5></a></li>
                            <li><a href="#"><h5>Log out</h5></a></li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav dashboardNavLeft">
                    <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard"><i class="fa fa-tachometer" aria-hidden="true"></i>Dashboard</a></li>
                    <li><a href="profile.html"><i class="fa fa-user" aria-hidden="true"></i>Profile</a></li>
                    <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/hotellist"><i class="fa fa-bed" aria-hidden="true"></i>Hotel</a></li>
                    <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/citylist"><i class="fa fa-map-marker" aria-hidden="true"></i>Serviceable City</a></li>
                    <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/locationlist"><i class="fa fa-map-marker" aria-hidden="true"></i>Location</a></li>
                    <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/packagelist"><i class="fa fa-cube" aria-hidden="true"></i>Packages</a></li>
                    <li><a class="active" href="setting.html"><i class="fa fa-cogs" aria-hidden="true"></i>Settings</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->

        </div><!-- /.container -->
    </nav>
</section>
<script>
            var serverUrl = '<?= $this->basePath().'/'; ?>';
</script>