<section class="settingSection" ng-app="location" ng-controller="locationController">
    <div class="container">
        <div class="row">
            <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
            <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
            <div class="col-xs-12">
                <div class="settingContent bg-ash">
                    <h4>Add Location</h4>
                    <div class="changePassword">
                        <p>Add Location</p>
                        <div class="row">
                            <form  method="post">
                                <div class="col-sm-12">
                                    <input type="text" class="form-control" id="inputPassword3" placeholder="location name" ng-model="location_name">
                                </div>
                                <div class="col-sm-12">
                                    <div class="primaryDrop">
                                        <select name="guiest_id3" id="city_id" class="width" sb="15257073" ng-model="city_id" ng-change="getHotel()" >
                                            <option value="">Select city</option>
                                            <option ng-repeat="name in cityList" value="{{name.id}}" ng-selected="name.id == city_id">{{name.city_name}}</option>
                                            
                                        </select>                                  
                                    </div>
                                </div>
                                
                                <div class="col-sm-12">
                                    <br>
                                    <div class="primaryDrop">
                                        <select name="guiest_id3" id="hotel" class="width" sb="15257073" ng-model="hotel_id"  >
                                            <option value="">Select hotel</option>
                                            <option ng-repeat="name in hotelList" value="{{name.id}}" ng-selected="name.id == hotel_id">{{name.name}}</option>
                                            
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <br>
                                    <div class="primaryDrop" class="area" >
                                        <textarea rows="4" id="description" cols="50"  placeholder="Describe hotel here..." ></textarea>
                                    </div>
                                </div>
<!--                                <div class="col-sm-12">
                                   
                                    <input type="file" class="form-control" id="uploadfile"  ng-model="upload_file">
                                </div>-->
                                <div class="row">
                                    <div class="col-sm-12 col-md-2">
                                        <p>Upload cover image</p>
                                    </div>  
                                    <div class="col-sm-12 col-md-10">
                                        <input type="file" id="uploadfile"  ng-model="upload_file" onchange="uploadCoverImage(this)">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 col-md-2">
                                        <p>Upload other images</p>
                                    </div>  
                                    <div class="col-sm-12 col-md-4">
                                        <input type="file" id="uploadfile"  ng-model="upload_file" onchange="uploadImageInTemp(this)">
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <img src="" id="profile-img-tag" width="100px" />
                                    </div>
                                </div>
                                <input type="hidden" name="location_id" id="location_id" ng-model="location_id" value="">
                                <input type="hidden" value="" name="tempfoldername" id="tempfoldername" ng-model="tempfoldername">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn buttonTransparent" ng-click="addlocation()">Add Location</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<style>
    .width{
        width:50%;
    }
</style>
<script>
   var app = angular.module('location', []);
   var cityList = app.value('cityList',<?= json_encode($this->cityList)?>);
   var hotelList = app.value('hotelList',<?= json_encode($this->hotelList)?>);
   var locationData = app.value('locationData',<?= json_encode($this->locationData)?>);
</script>
<script src="<?= $this->basePath() . '/public/js/addlocation.js' ?>"></script>
