<!-- ADD PACKAGE -->
<section class="settingSection">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="settingContent bg-ash">
                    <h4>Add Package</h4>
                    <!-- Change Password -->
                    <div class="changePassword">
                        <div class="row">
                            <form action="" method="post">
                                <div class="col-sm-12">
                                    <input type="text" class="form-control" id="inputPassword3" placeholder="Package Name">
                                </div>
                                <div class="col-sm-12">
                                    <input type="text" class="form-control" id="inputPassword3" placeholder="New Password">
                                </div>
                                <div class="col-sm-12">
                                    <input type="password" class="form-control" id="inputPassword3" placeholder="Confirm New Password">
                                </div>
                                <div class="col-sm-12">
                                    <button type="submit" class="btn buttonTransparent">Update Password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
