<!-- WELCOME SECTION -->
<section class="welcomeSection">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2>Hi Sergey Karen, Welcome to  <span> Star travel!</span></h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>
    </div>
</section>
<!-- BLOCK SECTION -->
<section class="blockSection">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="content-block">
                    <div class="media bg-blue-c">
                        <div class="media-body ">
                            <h4 class="media-heading">3,502</h4>
                            <p>Tour Packages</p>
                        </div>
                        <div class="media-right ">
                            <div class="icon bg-blue-b">
                                <i class="fa fa-gift" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                    <a href="" class="btn btn-content bg-blue-b">View Details<i class="fa fa-long-arrow-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="content-block">
                    <div class="media bg-red-c">
                        <div class="media-body">
                            <h4 class="media-heading">3,502</h4>
                            <p>Tour Hotels</p>
                        </div>
                        <div class="media-right">
                            <div class="icon bg-red-b">
                                <i class="fa fa-fort-awesome" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                    <a href="" class="btn btn-content bg-red-b">View Details<i class="fa fa-long-arrow-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="content-block">
                    <div class="media bg-green-c">
                        <div class="media-body">
                            <h4 class="media-heading">3,502</h4>
                            <p>Total Destination</p>
                        </div>
                        <div class="media-right">
                            <div class="icon bg-green-b">
                                <i class="fa fa-plane" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                    <a href="" class="btn btn-content bg-green-b">View Details <i class="fa fa-long-arrow-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="content-block">
                    <div class="media bg-orange-c">
                        <div class="media-body">
                            <h4 class="media-heading">3,502</h4>
                            <p>Total Bookings</p>
                        </div>
                        <div class="media-right">
                            <div class="icon bg-orange-b">
                                <i class="fa fa-car" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                    <a href="" class="btn btn-content bg-orange-b">View Details <i class="fa fa-long-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>