<!-- RECENT ACTIVITY SECTION -->
<section class="recentActivitySection">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 ">
                <div class="recentActivityContent bg-ash">
                    <div class="dashboardPageTitle">
                        <div class="row">
                            <div  class="col-sm-12 col-md-6 pull-left">   
                                <h2>Package List</h2>
                            </div>
                            <div  class="col-sm-12 col-md-6 pull-right">   
                                <ul class="list-inline detailsBtn">
                                    <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/addpackage" class="btn buttonTransparent buttonCustomPrimary">Add Package</a></li>
                                </ul>  
                            </div>    
                        </div>
                    </div>
                    <div class="table-responsive"  data-pattern="priority-columns">
                        <table class="table listingsTable">
                            <tr class="rowItem">
                                <td>Package Name</td>
                                <td>Location</td>
                                <td>Total seats</td>
                                <td>Booked Seat</td>
                                <td>trip Start Date</td>
                                <td>Trip End Date</td>
                                <td>Action</td>                                
                            </tr>
                            <tr class="rowItem">
                                <td> 3Day 2night</td>
                                <td>Manali</td>
                                <td>30</td>
                                <td>25</td>
                                <td>30 sep 2017</td>
                                <td>2 Oct 2017</td>
                                <td>
                                    <a href="#"><i class="fa fa-pencil"></i></a>
                                    <a href="#"><i class="fa fa-check"></i></a>
                                    <a href="#"><i class="fa fa-lock"></i></a>
                                    <a href="#"><i class="fa fa-trash-o"></i></a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
