    <!-- PAGE TITLE -->
    <section class="pageTitle">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="titleTable">
              <div class="titleTableInner">
                <div class="pageTitleInfo">
                  <h1>about us</h1>
                  <div class="under-border"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- PAGE CONTENT -->
    <section class="mainContentSection">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="aboutTitle">
              <h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h4>
              <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis</p>
            </div>
          </div>
        </div>
        <div class="row aboutItem">
          <div class="col-sm-4 col-xs-12">
            <div class="media">
              <a class="media-left" href="#"><i class="fa fa-bell" aria-hidden="true"></i></a>
              <div class="media-body">
                <h4 class="media-heading">Donec Vel Libero</h4>
                <p>Vestibulum ut lacus non lorem pharetra efficitur. Nunc nibh elit, consectetur quis dapibu.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="media">
              <a class="media-left" href="#"><i class="fa fa-briefcase" aria-hidden="true"></i></a>
              <div class="media-body">
                <h4 class="media-heading">Vivamus Laoreet</h4>
                <p>Aenean dictum dui quis interdum volutpat. Integer in magna sit amet efficitur nec.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="media">
              <a class="media-left" href="#"><i class="fa fa-cab" aria-hidden="true"></i></a>
              <div class="media-body">
                <h4 class="media-heading">Ullamcorper Congue</h4>
                <p>Etiam posuere lorem ac pharetra laoreet. Nam magna mi, eleifend ac vulputate ac.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="media">
              <a class="media-left" href="#"><i class="fa fa-camera" aria-hidden="true"></i></a>
              <div class="media-body">
                <h4 class="media-heading">Proin Libero Erat</h4>
                <p>Nunc eget sem ac lectus auctor viverra. Praesent sollicitudin leo velit sed, semper diam.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="media">
              <a class="media-left" href="#"><i class="fa fa-cloud" aria-hidden="true"></i></a>
              <div class="media-body">
                <h4 class="media-heading">Amaiging Tour</h4>
                <p>Nulla molestie leo vitae convallis sollicitudin. Nulla volutpat dapibus at pellentesque sem.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="media">
              <a class="media-left" href="#"><i class="fa fa-cutlery" aria-hidden="true"></i></a>
              <div class="media-body">
                <h4 class="media-heading">Cras Vestibulum</h4>
                <p>Aenean gravida, nisl et volutpat dapibus, nisl odio accumsan pretium lacus libero a lacus.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="whiteSection top-margin-0">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="sectionTitle">
              <h2><span>our Team</span></h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 col-xs-12">
            <div class="teamMember">
              <img src="<?=$this->basePath()?>/img/about-us/team-01.jpg" alt="">
              <div class="memberName">
                <h4>Sarah Harlas</h4>
                <p>Tour Guide</p>
              </div>
              <div class="maskingArea">
                <p>orem ipsum dolor sit amet, consectetur adipisicing elit commodo.</p>
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="teamMember">
              <img src="<?=$this->basePath()?>/img/about-us/team-02.jpg" alt="">
              <div class="memberName">
                <h4>Adam Smith</h4>
                <p>Tour Guide</p>
              </div>
              <div class="maskingArea">
                <p>orem ipsum dolor sit amet, consectetur adipisicing elit commodo.</p>
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="teamMember">
              <img src="<?=$this->basePath()?>/img/about-us/team-03.jpg" alt="">
              <div class="memberName">
                <h4>Jenet Immda</h4>
                <p>Tour Guide</p>
              </div>
              <div class="maskingArea">
                <p>orem ipsum dolor sit amet, consectetur adipisicing elit commodo.</p>
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>