    <!-- PAGE TITLE -->
    <section class="pageTitle" style="background-image:url(/ecogypsy/img/pages/page-title-bg5.jpg);">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="titleTable">
              <div class="titleTableInner">
                <div class="pageTitleInfo">
                  <h1>about us</h1>
                  <div class="under-border"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- PAGE CONTENT -->
    <section class="mainContentSection">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
              <div class="aboutTitle">
              <p  style="text-align: left;">We are a group of Gypsy souls who believe that journey is the true destination. Life’s all about journeying through the people, places and situations we believe and so it’s not just about going to natural surroundings but its beyond that. It’s about living those moments, become a part of nature, rather becoming nature itself.</p>
              <p style="text-align: left;">Traveling with us would mean nature walks, authentic local food over conversations with the local communities, lots of storytelling and sharing, folk music, art and cultures but the most prominent feature of our journeys is the lively moments you’d be collecting in your hearts. You’d be discovering your own self with these new friends you’d be making on the trip i.e. the locals and the co-travelers.</p>
              <p style="text-align: left;">We custom curatetravel trips for you that range from solo travelers (especially women) to couples, from friends to strangers, from spiritual retreats to yoga & wellness, bikers and back-packers, from reflective silos to weekend time-out and more. We also have fixed pocket friendly packages for your ease!</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="whiteSection top-margin-0">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="sectionTitle">
              <h2><span>our Team</span></h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 col-xs-12">
            <div class="teamMember">
              <img src="<?=$this->basePath()?>/img/about-us/team-01.jpg" alt="">
              <div class="memberName">
                <h4>Sarah Harlas</h4>
                <p>Tour Guide</p>
              </div>
              <div class="maskingArea">
                <p>orem ipsum dolor sit amet, consectetur adipisicing elit commodo.</p>
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="teamMember">
              <img src="<?=$this->basePath()?>/img/about-us/team-02.jpg" alt="">
              <div class="memberName">
                <h4>Adam Smith</h4>
                <p>Tour Guide</p>
              </div>
              <div class="maskingArea">
                <p>orem ipsum dolor sit amet, consectetur adipisicing elit commodo.</p>
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="teamMember">
              <img src="<?=$this->basePath()?>/img/about-us/team-03.jpg" alt="">
              <div class="memberName">
                <h4>Jenet Immda</h4>
                <p>Tour Guide</p>
              </div>
              <div class="maskingArea">
                <p>orem ipsum dolor sit amet, consectetur adipisicing elit commodo.</p>
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>