
<html>
<html lang="en">
<head>

  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Booking Step 3 - Personal Information - Star Travel</title>

  <!-- PLUGINS CSS STYLE -->
  <link href="plugins/jquery-ui/jquery-ui.css" rel="stylesheet">
  <link href="plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="plugins/rs-plugin/css/settings.css" media="screen">
  <link rel="stylesheet" type="text/css" href="plugins/selectbox/select_option1.css">
  <link rel="stylesheet" type="text/css" href="plugins/datepicker/datepicker.css">
  <link rel="stylesheet" type="text/css" href="plugins/isotope/jquery.fancybox.css">
  <link rel="stylesheet" type="text/css" href="plugins/isotope/isotope.css">

  <!-- GOOGLE FONT -->
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,600,700' rel='stylesheet' type='text/css'>

  <!-- CUSTOM CSS -->
  <link href="css/style.css" rel="stylesheet">
  <link rel="stylesheet" href="css/colors/default.css" id="option_color">

  <!-- FAVICON -->
  <link rel="shortcut icon" type="image/png" href="img/favicon.png"/>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->

</head>

<body class="body-wrapper ">
  <div class="main-wrapper">

    <!-- HEADER -->
    


    <!-- PAGE TITLE -->
    
    <!-- WHITE SECTION FILTER-->
    <section class="mainContentSection" style="margin-top:50px">
      <div class="container">
        <div class="row progress-wizard" style="border-bottom:0;">

          <div class="col-sm-6 col-xs-12 progress-wizard-step complete">
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="booking-1.html" class="progress-wizard-dot">
              <i class="fa fa-user" aria-hidden="true"></i>
              1. personal info
            </a>
          </div>

          <div class="col-sm-6 col-xs-12 progress-wizard-step complete">
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="javascript:void(0)" class="progress-wizard-dot">
              <i class="fa fa-check" aria-hidden="true"></i>
              2. Confirmation
            </a>
          </div>
        </div>
        <div class="row bookingConfirmed">
          <div class="col-xs-12">
            <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">Dismiss</span></button>
              <?php if($this->msg == 'success'){?>Thank you! Your booking is confirmed. Invoice Sent in your email address
			  <?php }else{?>
			  Somthing went wrong.
			  <?php }?>
            </div>
          </div>
          
        </div>
      </div>
    </section>

<!-- FOOTER -->
<footer>
  <div class="copyRight clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-push-6 col-xs-12">
          <ul class="list-inline">
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </div>
        <div class="col-sm-6 col-sm-pull-6 col-xs-12">
          <div class="copyRightText">
            <p>Copyright © 2016. All Rights Reserved by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
</div>


<!-- Login Modal --?
</body>

</html>

