    <!-- PAGE TITLE -->
    <section class="pageTitle" style="background-image:url(/ecogypsy/img/pages/page-title-bg5.jpg);">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="titleTable">
              <div class="titleTableInner">
                <div class="pageTitleInfo">
                  <h1>gallery</h1>
                  <div class="under-border"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- WHITE SECTION FILTER-->
    <section class="mainContentSection">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="filter-container isotopeFilters">
              <ul class="list-inline filter">
                <li class="active"><a href="#" data-filter="*">all places</a></li>
                <li><a href="#" data-filter=".asia">asia</a></li>
                <li><a href="#" data-filter=".america">america</a></li>
                <li><a href="#" data-filter=".europe">europe</a></li>
                <li><a href="#" data-filter=".africa">africa</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row isotopeContainer" id="container">
          <div class="col-sm-3 isotopeSelector asia">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-1.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-1.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector america">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-2.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-2.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector africa">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-3.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-3.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector asia">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-4.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-4.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector america">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-5.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-5.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector europe">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-6.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-6.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector europe">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-5.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-5.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

          <div class="col-sm-3 isotopeSelector africa">
            <article class="">
              <figure>
                <img src="<?=$this->basePath()?>/img/home/packages/packages-6.jpg" alt="">
                <h4>maldives tour</h4>
                <div class="overlay-background">
                  <div class="inner"></div>
                </div>
                <div class="overlay">
                  <a class="fancybox-pop" rel="portfolio-1" href="<?=$this->basePath()?>/img/home/packages/packages-6.jpg">
                    <span class="overlayInfo">
                      <h5>from <span>$1000</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 jan, 2016</p>
                    </span>
                  </a>
                </div>
              </figure>
            </article>
          </div>

        </div>
      </div>
    </section>