<section class="mainContentSection packagesSection">
    <div class="container">
        <br/>
        <div class="row">
            <div class="col-xs-12">
			<?php 
				foreach($this->packageList as $value){
                                    
			 ?>
                <div class="media packagesList">
                    <?php
                        if(!empty($this->image[$value['location_id']])){
                          
                    ?>
                    <a class="media-left fancybox-pop" src="<?=$this->image[$value['location_id']][0]?>">
                        <img class="media-object" src="<?=$this->image[$value['location_id']][0]?>" alt="Image">
                    </a>
                    <?php
                        }else{
                    ?>
                    <a class="media-left fancybox-pop" href="<?=$this->basePath()?>/img/packages/package-list-01.jpg">
                        <img class="media-object" src="<?=$this->basePath()?>/img/packages/package-list-01.jpg" alt="Image">
                    </a>
                        <?php }?>
                    <div class="media-body">
					
                        <div class="bodyLeft">
                            <h4 class="media-heading"><a href="single-package-right-sidebar.html"><?= $value['package_name']?></a></h4>
                            <div class="countryRating">
                                <span>Asia</span>
                                <ul class="list-inline rating">
                                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                </ul>
                            </div>
                            <p><?= $value['description']?></p>
                            <ul class="list-inline detailsBtn">
                                <li><span class="textInfo"><i class="fa fa-calendar" aria-hidden="true"></i> <?= date('d M,Y',strtotime($value['start_date']))?></span></li>
                                <li><span class="textInfo"><i class="fa fa-calendar" aria-hidden="true"></i> <?= date('d M,Y',strtotime($value['end_date']))?></span></li>
                            </ul>
                        </div>	
                        <div class="bodyRight">
                            <div class="bookingDetails">
                                <h2>INR <?=$value['price']?></h2>
                                <p>Per Person</p>
                                <a href="<?=$GLOBALS['SITE_APP_URL']?>index/detail?data=<?=$value['id']?>" class="btn buttonTransparent clearfix">Details</a>
                                <a  href="<?=$GLOBALS['SITE_APP_URL']?>index/booking?data=<?=$value['id']?>" class="btn buttonTransparent">Book</a>
                            </div>
                        </div>
                    </div>
                </div>
				
				<?php }?>
            </div>
        </div>
        <!--div class="row">
            <div class="col-xs-12">
                <div class="paginationCenter">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true"><i class="fa fa-long-arrow-left" aria-hidden="true"></i>Previous</span>
                            </a>
                        </li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">...</a></li>
                        <li><a href="#">9</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">Next<i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div-->
    </div>
</section>
