
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Booking Step 1 - Personal Information - Star Travel</title>

  <!-- PLUGINS CSS STYLE -->
  <link href="plugins/jquery-ui/jquery-ui.css" rel="stylesheet">
  <link href="plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="plugins/rs-plugin/css/settings.css" media="screen">
  <link rel="stylesheet" type="text/css" href="plugins/selectbox/select_option1.css">
  <link rel="stylesheet" type="text/css" href="plugins/datepicker/datepicker.css">
  <link rel="stylesheet" type="text/css" href="plugins/isotope/jquery.fancybox.css">
  <link rel="stylesheet" type="text/css" href="plugins/isotope/isotope.css">

  <!-- GOOGLE FONT -->
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,600,700' rel='stylesheet' type='text/css'>

  <!-- CUSTOM CSS -->
  <link href="css/style.css" rel="stylesheet">
  <link rel="stylesheet" href="css/colors/default.css" id="option_color">

  <!-- FAVICON -->
  <link rel="shortcut icon" type="image/png" href="img/favicon.png"/>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body class="body-wrapper ">
  <div class="main-wrapper">
    <!-- WHITE SECTION FILTER-->
    <section class="mainContentSection">
      <div class="container">
        <div class="row progress-wizard" style="border-bottom:0;">

          <div class="col-sm-6 col-xs-12 progress-wizard-step active">
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="javascript:void(0)" class="progress-wizard-dot">
              <i class="fa fa-user" aria-hidden="true"></i>
              1. personal info
            </a>
          </div>

          <div class="col-sm-6 col-xs-12 progress-wizard-step disabled">
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="booking-3.html" class="progress-wizard-dot">
              <i class="fa fa-check" aria-hidden="true"></i>
              2. Confirmation
            </a>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 col-sm-push-8 col-xs-12">
            <aside>
              <div class="infoTitle">
                <h2>Booking Details</h2>
              </div>
              <div class="bookDetailsInfo">
                <img src="img/booking/booking.jpg" alt="image">
                <div class="infoArea">
                  <ul class="list-unstyled">
                    <li><i class="fa fa-calendar" aria-hidden="true"></i>From:  <span><?= date('d M,Y',strtotime($this->data['start_date']))?></span></li>
                    <li><i class="fa fa-calendar" aria-hidden="true"></i>To:  <span><?= date('d M,Y',strtotime($this->data['end_date']))?></span></li>
                    <li><i class="fa fa-user" aria-hidden="true"></i></i>Guests:  <span><?= $this->data['number_of_person']?></span></li>
                  </ul>
                  
                </div>
              </div>
            </aside>
          </div>
          <div class="col-sm-8 col-sm-pull-4 col-xs-12">
            <div class="infoTitle">
              <h2>personal info</h2>
            </div>
            <div class="bookingForm">
              <form action="<?=$GLOBALS['SITE_APP_URL']?>index/createbooking" method="POST" role="form" class="form">
                <div class="row">
                  <div class="form-group col-sm-6 col-xs-12">
                    <label for="">First Name *</label>
                    <input type="text" class="form-control" name="first_name">
                  </div>
                  <div class="form-group col-sm-6 col-xs-12">
                    <label for="">Last Name </label>
                    <input type="text" class="form-control" name="last_name">
                  </div>
                  <div class="form-group col-sm-6 col-xs-12">
                    <label for="">Address *</label>
                    <input type="text" class="form-control" name="address">
                  </div>
                  
                  <div class="form-group col-sm-6 col-xs-12">
                    <label for="">Email *</label>
                    <input type="email" class="form-control" name="email">
                  </div>
				  <div class="form-group col-sm-6 col-xs-12">
                    <label for="">Mobile Number *</label>
                    <input type="number" class="form-control" name="mobile" maxlength="10">
                  </div>
                   <input type="hidden" class="form-control" name="location_id" value="<?= $this->data['location']?>">
				   <input type="hidden" class="form-control" name="package_id" value="0">
				   <input type="hidden" class="form-control" name="checkin_date" value="<?= date('Y-m-d',strtotime($this->data['start_date']))?>">
				   <input type="hidden" class="form-control" name="checkout_date" value="<?= date('Y-m-d',strtotime($this->data['end_date']))?>">
				   <input type="hidden" class="form-control" name="number_of_person" value="<?=$this->data['number_of_person']?>">
                 
                  <div class="col-xs-12">
                    <div class="buttonArea galleryBtnArea">
                      <ul class="list-inline">
                        <li class="pull-right"><input type="submit" value="Book"></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
<!-- FOOTER -->
<footer>
  <div class="copyRight clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-push-6 col-xs-12">
          <ul class="list-inline">
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </div>
        <div class="col-sm-6 col-sm-pull-6 col-xs-12">
          <div class="copyRightText">
            <p>Copyright © 2016. All Rights Reserved by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
</div>

<!-- Signup Modal -->
<div class="modal fade signupLoging" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modalContentCustom">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create your account</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="">
          <div class="form-group">
            <input type="text" class="form-control bg-ash" id="exampleInputEmail1" placeholder="Full Name">
          </div>
          <div class="form-group">
            <input type="email" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Email">
          </div>
          <div class="form-group">
            <input type="password" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> I agree to the terms of use and privacy.
            </label>
          </div>
          <button type="submit" class="btn btn-default">Login</button>
        </form>
        <div class="or">
          or
        </div>
        <a class="btn btn-default btnSocial"  href="#">Log in with facebook</a>
      </div>

      <div class="modal-footer">
          <div class="dontHaveAccount">
            <p>Don’t have an Account?<a href=""> Sign up</a></p>
          </div>
      </div>
    </div>
  </div>
</div>

<!-- Login Modal -->
<div class="modal fade signupLoging" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modalContentCustom">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Log in to your account</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="">
          <div class="form-group">
            <input type="email" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Email">
          </div>
          <div class="form-group">
            <input type="password" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember me
            </label>
            <a class="forgotPass clerfix" href="">Fogot Password?</a>
          </div>
          <button type="submit" class="btn btn-default">Login</button>
        </form>
        <div class="or">
          or
        </div>
        <a class="btn btn-default btnSocial"  href="#">Log in with facebook</a>
      </div>

      <div class="modal-footer">
          <div class="dontHaveAccount">
            <p>Don’t have an Account?<a href=""> Sign up</a></p>
          </div>
      </div>
    </div>
  </div>
</div>


<link href="options/optionswitch.css" rel="stylesheet">
<script src="options/optionswitcher.js"></script>
</body>

</html>

